const products = [
  {
    id: "01",
    name: "Handloom Pure Cotton Tant Saree in Grey",
    price: "200",
    color: "gray",
    type: ["Regional", "Handloom"],
    Style: [
      "Jamdani",
      "Tant",
      "Gadwal",
      "Kerala Kasavu",
      "Paithani",
      "Kalamkari",
    ],
    Occasion: ["Festive", "Casual", "Wedding", "Party"],
    Size: ["28", "30", "32", "34", "36", "38", "40", "42"],
    Plus: [
      "44",
      "46",
      "48",
      "50",
      "52",
      "54",
      "56",
      "58",
      "60",
      "62",
      "64",
      "66",
    ],
    Work: ["Traditional", "Resham", "Zari", "Sequins", "Contemporary"],
    TimetoDispatch: [
      "Ready to Ship",
      "Within 2 days",
      "Within 7 days",
      "Within 10 days",
      "Within 15 days",
      "More than 15 Days",
    ],
    Discount: ["10-15", "20-40"],
    thumbnail: "https://example.com/images/handloom_grey_thumbnail.jpg",
    gallery: [
      "https://example.com/images/handloom_grey_1.jpg",
      "https://example.com/images/handloom_grey_2.jpg",
      "https://example.com/images/handloom_grey_3.jpg",
    ],
  },
  {
    id: "02",
    name: "Silk Saree with Zari Border in Red",
    price: "350",
    color: "red",
    type: ["Festive", "Designer"],
    Style: ["Banarasi", "Kanjivaram", "Patola"],
    Occasion: ["Wedding", "Party"],
    Size: ["30", "32", "34", "36", "38", "40"],
    Plus: ["42", "44", "46", "48", "50"],
    Work: ["Zari", "Sequins", "Embroidered"],
    TimetoDispatch: ["Within 2 days", "Within 7 days"],
    Discount: ["15-20", "25-30"],
    thumbnail: "https://example.com/images/silk_red_thumbnail.jpg",
    gallery: [
      "https://example.com/images/silk_red_1.jpg",
      "https://example.com/images/silk_red_2.jpg",
      "https://example.com/images/silk_red_3.jpg",
    ],
  },
  {
    id: "03",
    name: "Georgette Embroidered Saree in Black",
    price: "250",
    color: "black",
    type: ["Party", "Contemporary"],
    Style: ["Chiffon", "Georgette", "Crepe"],
    Occasion: ["Party", "Evening"],
    Size: ["32", "34", "36", "38", "40"],
    Plus: ["42", "44", "46", "48", "50"],
    Work: ["Embroidered", "Sequins", "Stone Work"],
    TimetoDispatch: ["Ready to Ship", "Within 7 days"],
    Discount: ["10-20", "30-40"],
    thumbnail: "https://example.com/images/georgette_black_thumbnail.jpg",
    gallery: [
      "https://example.com/images/georgette_black_1.jpg",
      "https://example.com/images/georgette_black_2.jpg",
      "https://example.com/images/georgette_black_3.jpg",
    ],
  },
  {
    id: "04",
    name: "Chanderi Silk Saree in Green",
    price: "180",
    color: "green",
    type: ["Traditional", "Handloom"],
    Style: ["Chanderi", "Silk"],
    Occasion: ["Festive", "Casual"],
    Size: ["30", "32", "34", "36", "38"],
    Plus: ["40", "42", "44", "46", "48"],
    Work: ["Traditional", "Resham"],
    TimetoDispatch: ["Within 2 days", "Within 10 days"],
    Discount: ["5-10", "15-20"],
    thumbnail: "https://example.com/images/chanderi_green_thumbnail.jpg",
    gallery: [
      "https://example.com/images/chanderi_green_1.jpg",
      "https://example.com/images/chanderi_green_2.jpg",
      "https://example.com/images/chanderi_green_3.jpg",
    ],
  },
  {
    id: "05",
    name: "Tussar Silk Saree in Beige",
    price: "300",
    color: "beige",
    type: ["Handloom", "Designer"],
    Style: ["Tussar", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["28", "30", "32", "34", "36", "38"],
    Plus: ["40", "42", "44", "46", "48"],
    Work: ["Zari", "Embroidered", "Resham"],
    TimetoDispatch: ["Ready to Ship", "Within 15 days"],
    Discount: ["20-25", "30-35"],
    thumbnail: "https://example.com/images/tussar_beige_thumbnail.jpg",
    gallery: [
      "https://example.com/images/tussar_beige_1.jpg",
      "https://example.com/images/tussar_beige_2.jpg",
      "https://example.com/images/tussar_beige_3.jpg",
    ],
  },
  {
    id: "06",
    name: "Cotton Printed Saree in Blue",
    price: "150",
    color: "blue",
    type: ["Casual", "Handloom"],
    Style: ["Cotton", "Printed"],
    Occasion: ["Casual", "Daily Wear"],
    Size: ["32", "34", "36", "38", "40"],
    Plus: ["42", "44", "46", "48"],
    Work: ["Printed", "Contemporary"],
    TimetoDispatch: ["Ready to Ship", "Within 2 days"],
    Discount: ["5-10", "10-15"],
    thumbnail: "https://example.com/images/cotton_blue_thumbnail.jpg",
    gallery: [
      "https://example.com/images/cotton_blue_1.jpg",
      "https://example.com/images/cotton_blue_2.jpg",
      "https://example.com/images/cotton_blue_3.jpg",
    ],
  },
  {
    id: "07",
    name: "Banarasi Silk Saree in Pink",
    price: "400",
    color: "pink",
    type: ["Festive", "Traditional"],
    Style: ["Banarasi", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42", "44"],
    Work: ["Zari", "Resham", "Sequins"],
    TimetoDispatch: ["Within 2 days", "Within 10 days"],
    Discount: ["10-15", "20-25"],
    thumbnail: "https://example.com/images/banarasi_pink_thumbnail.jpg",
    gallery: [
      "https://example.com/images/banarasi_pink_1.jpg",
      "https://example.com/images/banarasi_pink_2.jpg",
      "https://example.com/images/banarasi_pink_3.jpg",
    ],
  },
  {
    id: "08",
    name: "Paithani Silk Saree in Purple",
    price: "450",
    color: "purple",
    type: ["Traditional", "Handloom"],
    Style: ["Paithani", "Silk"],
    Occasion: ["Festive", "Wedding"],
    Size: ["30", "32", "34", "36", "38"],
    Plus: ["40", "42", "44", "46"],
    Work: ["Traditional", "Zari"],
    TimetoDispatch: ["Within 7 days", "Within 15 days"],
    Discount: ["15-20", "25-30"],
    thumbnail: "https://example.com/images/paithani_purple_thumbnail.jpg",
    gallery: [
      "https://example.com/images/paithani_purple_1.jpg",
      "https://example.com/images/paithani_purple_2.jpg",
      "https://example.com/images/paithani_purple_3.jpg",
    ],
  },
  {
    id: "09",
    name: "Kalamkari Cotton Saree in Yellow",
    price: "220",
    color: "yellow",
    type: ["Casual", "Handloom"],
    Style: ["Kalamkari", "Cotton"],
    Occasion: ["Casual", "Daily Wear"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42"],
    Work: ["Printed", "Hand Painted"],
    TimetoDispatch: ["Ready to Ship", "Within 7 days"],
    Discount: ["10-15", "20-30"],
    thumbnail: "https://example.com/images/kalamkari_yellow_thumbnail.jpg",
    gallery: [
      "https://example.com/images/kalamkari_yellow_1.jpg",
      "https://example.com/images/kalamkari_yellow_2.jpg",
      "https://example.com/images/kalamkari_yellow_3.jpg",
    ],
  },
  {
    id: "10",
    name: "Kerala Kasavu Saree in White and Gold",
    price: "260",
    color: "white and gold",
    type: ["Traditional", "Handloom"],
    Style: ["Kasavu", "Cotton"],
    Occasion: ["Festive", "Casual"],
    Size: ["30", "32", "34", "36", "38", "40"],
    Plus: ["42", "44", "46", "48", "50"],
    Work: ["Zari", "Traditional"],
    TimetoDispatch: ["Ready to Ship", "Within 15 days"],
    Discount: ["10-20", "25-30"],
    thumbnail: "https://example.com/images/kasavu_white_gold_thumbnail.jpg",
    gallery: [
      "https://example.com/images/kasavu_white_gold_1.jpg",
      "https://example.com/images/kasavu_white_gold_2.jpg",
      "https://example.com/images/kasavu_white_gold_3.jpg",
    ],
  },
  {
    id: "11",
    name: "Mysore Silk Saree in Blue",
    price: "350",
    color: "blue",
    type: ["Traditional", "Handloom"],
    Style: ["Mysore", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42"],
    Work: ["Zari", "Embroidered"],
    TimetoDispatch: ["Within 2 days", "Within 10 days"],
    Discount: ["10-15", "20-25"],
    thumbnail: "https://example.com/images/mysore_blue_thumbnail.jpg",
    gallery: [
      "https://example.com/images/mysore_blue_1.jpg",
      "https://example.com/images/mysore_blue_2.jpg",
      "https://example.com/images/mysore_blue_3.jpg",
    ],
  },
  {
    id: "12",
    name: "Chikankari Georgette Saree in Peach",
    price: "280",
    color: "peach",
    type: ["Contemporary", "Handloom"],
    Style: ["Chikankari", "Georgette"],
    Occasion: ["Party", "Casual"],
    Size: ["30", "32", "34", "36"],
    Plus: ["38", "40", "42", "44"],
    Work: ["Embroidered", "Resham"],
    TimetoDispatch: ["Ready to Ship", "Within 7 days"],
    Discount: ["5-10", "15-20"],
    thumbnail: "https://example.com/images/chikankari_peach_thumbnail.jpg",
    gallery: [
      "https://example.com/images/chikankari_peach_1.jpg",
      "https://example.com/images/chikankari_peach_2.jpg",
      "https://example.com/images/chikankari_peach_3.jpg",
    ],
  },
  {
    id: "13",
    name: "Bandhani Silk Saree in Red",
    price: "320",
    color: "red",
    type: ["Traditional", "Handloom"],
    Style: ["Bandhani", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42"],
    Work: ["Tie-Dye", "Resham"],
    TimetoDispatch: ["Within 2 days", "Within 15 days"],
    Discount: ["10-20", "25-30"],
    thumbnail: "https://example.com/images/bandhani_red_thumbnail.jpg",
    gallery: [
      "https://example.com/images/bandhani_red_1.jpg",
      "https://example.com/images/bandhani_red_2.jpg",
      "https://example.com/images/bandhani_red_3.jpg",
    ],
  },
  {
    id: "14",
    name: "Kanchipuram Silk Saree in Gold",
    price: "500",
    color: "gold",
    type: ["Festive", "Traditional"],
    Style: ["Kanchipuram", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["32", "34", "36", "38"],
    Plus: ["40", "42", "44"],
    Work: ["Zari", "Traditional"],
    TimetoDispatch: ["Ready to Ship", "Within 7 days"],
    Discount: ["15-20", "25-30"],
    thumbnail: "https://example.com/images/kanchipuram_gold_thumbnail.jpg",
    gallery: [
      "https://example.com/images/kanchipuram_gold_1.jpg",
      "https://example.com/images/kanchipuram_gold_2.jpg",
      "https://example.com/images/kanchipuram_gold_3.jpg",
    ],
  },
  {
    id: "15",
    name: "Baluchari Silk Saree in Green",
    price: "400",
    color: "green",
    type: ["Traditional", "Handloom"],
    Style: ["Baluchari", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42"],
    Work: ["Zari", "Resham"],
    TimetoDispatch: ["Within 2 days", "Within 15 days"],
    Discount: ["10-15", "20-25"],
    thumbnail: "https://example.com/images/baluchari_green_thumbnail.jpg",
    gallery: [
      "https://example.com/images/baluchari_green_1.jpg",
      "https://example.com/images/baluchari_green_2.jpg",
      "https://example.com/images/baluchari_green_3.jpg",
    ],
  },
  {
    id: "16",
    name: "Gadwal Silk Saree in Black",
    price: "370",
    color: "black",
    type: ["Traditional", "Handloom"],
    Style: ["Gadwal", "Silk"],
    Occasion: ["Wedding", "Party"],
    Size: ["30", "32", "34", "36"],
    Plus: ["38", "40", "42", "44"],
    Work: ["Zari", "Embroidered"],
    TimetoDispatch: ["Within 7 days", "Within 10 days"],
    Discount: ["15-20", "25-30"],
    thumbnail: "https://example.com/images/gadwal_black_thumbnail.jpg",
    gallery: [
      "https://example.com/images/gadwal_black_1.jpg",
      "https://example.com/images/gadwal_black_2.jpg",
      "https://example.com/images/gadwal_black_3.jpg",
    ],
  },
  {
    id: "17",
    name: "Pochampally Ikkat Saree in Blue",
    price: "330",
    color: "blue",
    type: ["Traditional", "Handloom"],
    Style: ["Ikkat", "Silk"],
    Occasion: ["Festive", "Wedding"],
    Size: ["28", "30", "32", "34"],
    Plus: ["36", "38", "40", "42"],
    Work: ["Ikkat", "Handwoven"],
    TimetoDispatch: ["Ready to Ship", "Within 7 days"],
    Discount: ["10-15", "20-25"],
    thumbnail: "https://example.com/images/ikkat_blue_thumbnail.jpg",
    gallery: [
      "https://example.com/images/ikkat_blue_1.jpg",
      "https://example.com/images/ikkat_blue_2.jpg",
      "https://example.com/images/ikkat_blue_3.jpg",
    ],
  },
  {
    id: "18",
    name: "Uppada Silk Saree in Purple",
    price: "350",
    color: "purple",
    type: ["Festive", "Handloom"],
    Style: ["Uppada", "Silk"],
    Occasion: ["Wedding", "Festive"],
    Size: ["30", "32", "34", "36", "38"],
    Plus: ["40", "42", "44", "46"],
    Work: ["Zari", "Resham"],
    TimetoDispatch: ["Within 2 days", "Within 10 days"],
    Discount: ["10-15", "20-30"],
    thumbnail: "https://example.com/images/uppada_purple_thumbnail.jpg",
    gallery: [
      "https://example.com/images/uppada_purple_1.jpg",
      "https://example.com/images/uppada_purple_2.jpg",
      "https://example.com/images/uppada_purple_3.jpg",
    ],
  },
];

export default {
  products,
};
